from django.shortcuts import render
from django.views import View
from rest_framework import views as REST_Views
from rest_framework.response import Response

from pressfits.model import AxisymmetricPressFitModel, Material
from pressfits.serializers import PressSerializer


class PressFit(View):
    def get(self, request):
        return render(request, "pressfits/page.html")


class PressView(REST_Views.APIView):
    def get(self, request):

        # Process post data
        p_0_material = self.get_material(request, "p_0_")
        p_1_material = self.get_material(request, "p_1_")
        [p_0_id, p_0_od, p_0_length] = self.get_part_parameters(request, "p_0_")
        [p_1_id, p_1_od, p_1_length] = self.get_part_parameters(request, "p_1_")
        x_offset = request.POST.get["x_offset"]

        model = AxisymmetricPressFitModel(
            p_0_id,
            p_1_id,
            p_0_od,
            p_1_od,
            p_0_length,
            p_1_length,
            x_offset,
            "Press_Fit",
        )
        model.run_model(p_0_material, p_1_material)
        model_data = {
            "mesh_string": model.inp_str,
            "elemental_results_string": model.get_elemental_results_str(),
            "nodal_results_string": model.get_nodal_results_str(),
        }

        results = PressSerializer(model_data).data
        return Response(results)

    @staticmethod
    def get_material(request, part_prefix):
        """Gets a material from a request post description

        Args:
            request (Request): Request containing post parameters
            part_prefix (String): Prefix used for parameters. Eg. p_0_

        Returns:
            Material: Material generated by the post paramters
        """

        return Material(
            name=f"{part_prefix}_mat",
            youngs_modulus=request.POST.get[f"{part_prefix}_youngs_modulus"],
            poissons_ratio=request.post.get[f"{part_prefix}_poissons_ratio"],
        )

    @staticmethod
    def get_part_parameters(request, part_prefix):
        """Gets a material from a request post description

        Args:
            request (Request): Request containing post parameters
            part_prefix (String): Prefix used for parameters. Eg. p_0_

        Returns:
            tuple: Inner Diameter, Outer Diameter, Length, x_offset
        """

        return (
            request.POST.get[f"{part_prefix}_inner_diameter"],
            request.post.get[f"{part_prefix}_outer_diameter"],
            request.post.get[f"{part_prefix}_length"],
        )
